import { Inter } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/context/language-context";
import Navigation from "@/components/navigation";
import FooterWrapper from "@/components/footer-wrapper";
import logo from "../../public/logos.png"
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Ainova",
  description: "Generated by Ainova",
  icons: {
    icon: "/logos.png",
    
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      
      <body className={`${inter.variable} antialiased`}>
        <LanguageProvider>
        <Navigation />
        {children}
        <FooterWrapper />
        </LanguageProvider>
      </body>
    </html>
  );
}